<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Monica Dang" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Students&#39; Test Scores Analysis</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Students&#39; Test Scores Analysis</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="introduction" class="section level2">
<h2>INTRODUCTION</h2>
<p><em>In the fall, I will be pursuing a master’s in social work, and one of the main aspects in the field is looking at inequalities that are prevelant in society today. Decades of research have been done to understand the research inequality that prevails our country today. This dataset looks at a student’s test performance. The categorical variables include a student’s gender (‘gender’) and whether or not they had completed a test preparation course (‘test preparation score’) which will be indicated by ‘completed’, or ‘not completed’. The numeric variables include, ‘math score, ’reading score’ and ‘writing score’ which measures how well a student scored on these test sections. There are a total of 189 observations for each of the variables.</em></p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.3     ✓ purrr   0.3.4
## ✓ tibble  3.0.4     ✓ dplyr   1.0.2
## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
## ✓ readr   1.4.0     ✓ forcats 0.5.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>#Loading our dataset into R studio 
student &lt;- read_csv(&quot;StudentsPerformance.csv&quot;)</code></pre>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   gender = col_character(),
##   `race/ethnicity` = col_character(),
##   `parental level of education` = col_character(),
##   lunch = col_character(),
##   `test preparation course` = col_character(),
##   `math score` = col_double(),
##   `reading score` = col_double(),
##   `writing score` = col_double()
## )</code></pre>
<pre class="r"><code>#Selecting the main variables to focus on
student &lt;- student %&gt;% select(gender, `test preparation course`, `math score`, `reading score`, `writing score`)

#Renaming the variables 
names(student)[names(student) == &quot;test preparation course&quot;] &lt;- &quot;test&quot;
names(student)[names(student) == &quot;math score&quot;] &lt;- &quot;math&quot;
names(student)[names(student) == &quot;reading score&quot;] &lt;- &quot;reading&quot;
names(student)[names(student) == &quot;writing score&quot;] &lt;- &quot;writing&quot;

#Set the variable &#39;gender&#39; as a binary variable. 
student1 &lt;- student %&gt;% mutate(y=ifelse(gender==&quot;female&quot;,1,0))
student1$gender &lt;- factor(student1$gender,levels=c(&quot;female&quot;, &quot;male&quot;))</code></pre>
</div>
<div id="manova-testing" class="section level2">
<h2>MANOVA TESTING</h2>
<p><em>A MANOVA test was conducted in order to see if math, reading and writing scores show a mean difference across gender. The null hypothesis will suggest that all the means of the three groups (math, reading, writing) are equal, whereas the alternative hypothesis suggests that at least one of these three groups’ mean will differ. We find the p-value is significant (2.2e-16) and say that one of the response variables differ. A univariate ANOVA was conducted and suggests that all three resopnse variables are significant. Post-hoc tests were conducted and in total, 116 tests were conducted, which included 1 MANOVA test, 3 ANOVA tests, and 112 t-tests. The probability of at least one type I error is 0.996 and after adjusting it (bonferroni correction) it is now 0.00043. Most likely the MANOVA assumptions were not met because this data was most likely not randomly collected.</em></p>
<pre class="r"><code>#A MANOVA test was conducted to determine if math, reading and writing scores show a mean difference across gender. 
man1 &lt;- manova(cbind(math, reading, writing)~test, data=student)
summary(man1)</code></pre>
<pre><code>##            Df  Pillai approx F num Df den Df    Pr(&gt;F)    
## test        1 0.13953   53.833      3    996 &lt; 2.2e-16 ***
## Residuals 998                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#Univariate ANOVAs tests were ran due to the significance of the MANOVA test
summary.aov(man1)</code></pre>
<pre><code>##  Response math :
##              Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## test          1   7253  7253.2  32.543 1.536e-08 ***
## Residuals   998 222436   222.9                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response reading :
##              Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## test          1  12449 12448.7  61.963 9.082e-15 ***
## Residuals   998 200504   200.9                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response writing :
##              Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## test          1  22591 22591.4  108.35 &lt; 2.2e-16 ***
## Residuals   998 208086   208.5                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#Post-hoc tests was conducted 
pairwise.t.test(student$math, student$test, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  student$math and student$test 
## 
##      completed
## none 1.5e-08  
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(student$reading, student$test, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  student$reading and student$test 
## 
##      completed
## none 9.1e-15  
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(student$writing, student$test, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  student$writing and student$test 
## 
##      completed
## none &lt;2e-16   
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#Calculating the probability of atleast one type I error
Type1ErrorCount &lt;- replicate(5000,{
  pvals&lt;-NULL
    for(i in 1:112){
      samp1 &lt;- rnorm(20, mean=0)
      samp2 &lt;- rnorm(20, mean=0)
      pvals[i] &lt;- t.test(samp1, samp2, var.eq=T)$p.val
    }
  sum(pvals&lt;.05)
})
mean(Type1ErrorCount&gt;0)</code></pre>
<pre><code>## [1] 0.9966</code></pre>
<pre class="r"><code>#Adjusting the signficance level
0.05/116</code></pre>
<pre><code>## [1] 0.0004310345</code></pre>
</div>
<div id="randomization-test" class="section level2">
<h2>RANDOMIZATION TEST</h2>
<p><em>A two-sample t-test was conducted in order to see if there was a mean difference in math scores between gender (male and female). The null hypothesis is that the math score difference between gender is a value of 0. The alternative hypothesis is that there is a difference in math score between gender other than 0. The test was conducted, and we found that there is a signficance in the results because the p-value is 8.24e-08. This means that the null hypothesis is rejected and that there is a difference in scores between genders.</em></p>
<pre class="r"><code>#A randomization test was conducted to find the mean difference
t.test(data=student1, math ~ y)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  math by y
## t = 5.398, df = 997.98, p-value = 8.421e-08
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  3.242813 6.947209
## sample estimates:
## mean in group 0 mean in group 1 
##        68.72822        63.63320</code></pre>
<pre class="r"><code>#A plot was created to visualize the results
ggplot(student1, aes(math,fill=y)) + geom_histogram(bins=4) + facet_wrap(~y) + theme(legend.position=&quot;none&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
</div>
<div id="linear-regression-model" class="section level2">
<h2>LINEAR REGRESSION MODEL</h2>
<p><em>The predicted reading score of a female student with a math score of 0 is predicted to be at a value of 5.51. The score of male students with a math score of 0 is predicted to score 11.48 less than female students with a math score of 0.</em></p>
<p><em>The proportion of the variation in the outcome is explained by the model of a value of 0.8184. When checking the assumptions of linearity, normality and homoskedasticity, we find that the assumptions seem to be good and passes. This is because the residuals look normally scattered and distributed. Whereas, looking at normality with the histogram, there seems to be a normal distribution. When recomputing the regression results with robust standard errors via coeftest, we find that there is an increase of standard error resulting in a larger p-value and smaller t-statistic.</em></p>
<pre class="r"><code>student1$reading_c &lt;- student1$reading - mean(student1$reading)
student1$math_c &lt;- student1$math - mean(student1$math)
fit &lt;- lm(reading_c~gender*math_c, data=student1)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = reading_c ~ gender * math_c, data = student1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -19.2390  -4.2298   0.1665   4.3036  19.1831 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         5.51159    0.27722   19.88   &lt;2e-16 ***
## gendermale        -11.47547    0.40017  -28.68   &lt;2e-16 ***
## math_c              0.84392    0.01769   47.70   &lt;2e-16 ***
## gendermale:math_c   0.01539    0.02655    0.58    0.562    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.231 on 996 degrees of freedom
## Multiple R-squared:  0.8184, Adjusted R-squared:  0.8178 
## F-statistic:  1496 on 3 and 996 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#A regression plot was created to visualize the interaction
ggplot(student1, aes(reading_c, math_c, color=gender)) +geom_smooth(methods=&quot;lm&quot;)</code></pre>
<pre><code>## Warning: Ignoring unknown parameters: methods</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>#Linearity and homoskedasticity was checked
resid &lt;-fit$residuals; fitvals&lt;-fit$fitted.values
ggplot() + geom_point(aes(fitvals,resid)) + geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<pre class="r"><code>#Normality was checked
ggplot() + geom_histogram(aes(resid), bins=25)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-3.png" width="672" /></p>
<pre class="r"><code>#Looked at uncorrected SEs
library(sandwich); library(lmtest)</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code>summary(fit)$coef[,1:2]</code></pre>
<pre><code>##                       Estimate Std. Error
## (Intercept)         5.51159180 0.27721852
## gendermale        -11.47546538 0.40017486
## math_c              0.84391547 0.01769090
## gendermale:math_c   0.01539382 0.02654545</code></pre>
<pre class="r"><code>#Looked at corrected SEs
coeftest(fit, vcov=vcovHC(fit))[,1:2]</code></pre>
<pre><code>##                       Estimate Std. Error
## (Intercept)         5.51159180 0.26204762
## gendermale        -11.47546538 0.40269335
## math_c              0.84391547 0.01640411
## gendermale:math_c   0.01539382 0.02662458</code></pre>
</div>
<div id="linear-regression-model-with-boot-strap-errors" class="section level2">
<h2>LINEAR REGRESSION MODEL WITH BOOT STRAP ERRORS</h2>
<p><em>Unforunately, I was not able to knit the results due to an error when knitting, so the code had to be deleted, but my standard error did change in comparison to the original and robust standard errors. Sorry about this.</em></p>
<pre class="r"><code>fit &lt;- lm(reading_c~gender*math_c, data=student1)
res1 &lt;- fit$residuals
fittedvalues &lt;- fit$fitted.values</code></pre>
</div>
<div id="logistic-regression-model-predicting-a-binary-variable" class="section level2">
<h2>LOGISTIC REGRESSION MODEL PREDICTING A BINARY VARIABLE</h2>
<p><em>By controlling for the student’s writing score, for every 1 point increase in a student’s reading score, the odds of it being male or female change by a factor of -0.074317. By controlling the reading score, for every 1 point increase in a student’s writing score, the odds of it being male or female change by a factor of 0.112474.</em></p>
<p><em>Looking at the accuracy value of 0.823 helps us to determine the proportion of correctly classified outcomes of students. The TPR value (the true positive rate) is 0.8170478, which is the proportion of male students correctly classified. The TNR value (true negative rate) is 0.8285164 is the probability of female students correctly classified. The PPV (the positive predicted value) is the proportion of classified males who actually are males. The AUC value is .9096189, which can be considered great. After generating a ROC curve/plot, the AUC comes out to be at a value of .9096189, which the value is considered great.</em></p>
<pre class="r"><code>library(plotROC)

#A logistic regression model
  fit1 &lt;- glm(y~reading_c+math_c, data=student1, family=&quot;binomial&quot;)
coeftest(fit1)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##              Estimate Std. Error  z value Pr(&gt;|z|)    
## (Intercept)  0.104258   0.090906   1.1469   0.2514    
## reading_c    0.306828   0.019224  15.9605   &lt;2e-16 ***
## math_c      -0.285003   0.018055 -15.7855   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#Created a confusion matrix
prob &lt;- predict(fit1, type=&quot;response&quot;)
table(predict=as.numeric(prob&gt;.5), truth=student1$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict    0    1  Sum
##     0    393   88  481
##     1     89  430  519
##     Sum  482  518 1000</code></pre>
<pre class="r"><code>#Accuracy
((393+430)/1000)</code></pre>
<pre><code>## [1] 0.823</code></pre>
<pre class="r"><code>#TPR
393/481</code></pre>
<pre><code>## [1] 0.8170478</code></pre>
<pre class="r"><code>#TNR
430/519</code></pre>
<pre><code>## [1] 0.8285164</code></pre>
<pre class="r"><code>#PPV
393/482</code></pre>
<pre><code>## [1] 0.8153527</code></pre>
<pre class="r"><code>#AUC
class_diag(prob, student1$y)</code></pre>
<pre><code>##     acc      sens      spec       ppv       auc
## 1 0.823 0.8301158 0.8153527 0.8285164 0.9096189</code></pre>
<pre class="r"><code>#A density plot was created to visualize the results
student1$logit &lt;- predict(fit1,type = &quot;link&quot;)
student1 %&gt;% mutate(y=as.factor(y)) %&gt;% ggplot(aes(logit, color=y, fill=y)) +geom_density(alpha=.5) + geom_vline(xintercept=0) + xlab(&quot;predictor(logit)&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>#An ROC curve was created to visualize
ROC &lt;-ggplot(student1)+ geom_roc(aes(d=y, m=prob), n.cuts=0)
ROC</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<pre class="r"><code>#AUC was calculated
calc_auc(ROC)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.9096189</code></pre>
</div>
<div id="logistic-regression-with-all-variables" class="section level2">
<h2>LOGISTIC REGRESSION WITH ALL VARIABLES</h2>
<p><em>Looking at the accuracy value of 0.664 helps us to determine the proportion of correctly classified outcomes of students. The TPR value (the true positive rate) is 0.8301158, which is the proportion of male students correctly classified. The TNR value (true negative rate) is 0.8153527 is the probability of female students correctly classified. The PPV (the positive predicted value) is the proportion of classified males who actually are males. The AUC value is 0.9096189, which can be considered great. After generating a ROC curve/plot, the AUC comes out to be at a value of 0.9096189, which the value is considered great.</em>
<em>When calculating the out-of-sample classification, the AUC came out to be at a value of 0.9601502, which is higher than the in-sample calculation, and is considered to be great. After conducting a LASSO, the ‘test’, ‘math’, ‘reading’ and ‘writing’ variables were retained. After conducting a 10-fold CV using the variables lasso selected, the model’s out-of-sample AUC is 0.9160367, which in comparison is about the same value to the logistic regression’s AUC value of 0.9096189.</em></p>
<pre class="r"><code>student2 &lt;- student1 %&gt;%select(test, math, reading, writing, y)

#A logistic regression model was created
fit2 &lt;- glm(y~., data=student2, family=&quot;binomial&quot;)
coeftest(fit2)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##              Estimate Std. Error  z value  Pr(&gt;|z|)    
## (Intercept) -5.546421   0.717147  -7.7340 1.042e-14 ***
## testnone     2.366934   0.296287   7.9886 1.364e-15 ***
## math        -0.422531   0.028405 -14.8752 &lt; 2.2e-16 ***
## reading      0.031369   0.028371   1.1057    0.2689    
## writing      0.438837   0.037790  11.6126 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>prob1 &lt;- predict(fit2, type=&quot;response&quot;)

#Computing in-sample classification diagnostics
class_diag(prob,student2$y)</code></pre>
<pre><code>##     acc      sens      spec       ppv       auc
## 1 0.823 0.8301158 0.8153527 0.8285164 0.9096189</code></pre>
<pre class="r"><code>#A 10-fold CV was performed
set.seed(1234)
k=10

data&lt;-student2[sample(nrow(student2)),]
fold&lt;-cut(seq(1:nrow(student2)), breaks=k, labels=FALSE)

diags&lt;-NULL
for(i in 1:k){
  train&lt;-data[fold!=i,]
  tests&lt;-data[fold==i,]
  truth&lt;-tests$y
  fit&lt;-glm(y~., data=student2,family=&quot;binomial&quot;)
  probp&lt;-predict(fit,newdata=tests, type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(probp,truth))
}
#Computing out-of-sample classification diagnostics
summarize_all(diags,mean)</code></pre>
<pre><code>##     acc      sens      spec       ppv       auc
## 1 0.887 0.8950802 0.8765691 0.8893237 0.9601502</code></pre>
<pre class="r"><code>#Grab Response/Predictor
library(glmnet)</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loaded glmnet 4.0-2</code></pre>
<pre class="r"><code>y&lt;-as.matrix(student2$y) 
x&lt;-model.matrix(y~., data=student2)[,-1] 
head(x)</code></pre>
<pre><code>##   testnone math reading writing
## 1        1   72      72      74
## 2        0   69      90      88
## 3        1   90      95      93
## 4        1   47      57      44
## 5        1   76      78      75
## 6        1   71      83      78</code></pre>
<pre class="r"><code>cvs &lt;-cv.glmnet(x, y, family=&quot;binomial&quot;)

#Lasso was conducted
lassos &lt;-glmnet(x, y, family=&quot;binomial&quot;, lambda=cvs$lambda.1se)
coef(lassos)</code></pre>
<pre><code>## 5 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                       s0
## (Intercept) -3.297672242
## testnone     1.326575217
## math        -0.266918598
## reading      0.006527403
## writing      0.289774252</code></pre>
<pre class="r"><code>#A 10-fold CV test was conducted on LASSO
set.seed(1234) 
k=10

data&lt;-student2%&gt;%sample_frac
fold1&lt;-ntile(1:nrow(data),n=10)

diags&lt;-NULL
for(i in 1:k){
  train&lt;-data[fold1!=i,]
  test&lt;-data[fold1==i,]
  truth&lt;-test$y
  fit&lt;-glm(y~test+math+reading,
           data=train, family=&quot;binomial&quot;)
  prob1&lt;-predict(fit, newdata=test, type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(prob1,truth))
}
diags%&gt;%summarize_all(mean)</code></pre>
<pre><code>##     acc      sens      spec       ppv       auc
## 1 0.828 0.8352537 0.8192031 0.8340442 0.9160367</code></pre>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
